### ISSUE TITLE
metalet

### ISSUE THREAD

**Issue by loyloy1971** [metalet-labs/metalet-extension-next#2]
地址：1Nc1zjzowZQMwnEGV6o9mKCuTU4qMEpqnF
1、地址的SPACE的余额显示不正确，多了。
2、ticket.fan不能交易，打开SWAP不显示钱包中的WBTC和待交易的MRC20代币余额，不过单独打开钱包可以显示。

**Comment by loyloy1971** [comment]
升到3.4了。没有解决。现在发帖显示“user canceled",ticket仍不显示余额。

**Comment by loyloy1971** [comment]
只有showmoney显示的SPACE余额是正确的，SHOW3-V1也能正常发贴。mvcscan.com,mvcscan,space以及metalet显示的SPACE余额都不正确，其中Meralet与mvcscan.com显示的一致，而mvcscan.space则显示了另一个不同的错误余额。

**Comment by AricRedemption** [comment]
Please provide your mvc address. @loyloy1971

**Comment by AricRedemption** [comment]
In Showmoney or Show3-v1, the balance you see might be the balance of the xpub, which includes multiple addresses. Currently, in Metalet, it shows the balance for a single address.

**Comment by loyloy1971** [comment]
MVC地址:   1Nc1zjzowZQMwnEGV6o9mKCuTU4qMEpqnF        
如果metalet显示的是单地址，showmoney是多地址，为什么metalet显示的余额反而更多？

**Comment by loyloy1971** [comment]
还有，目前ticket正常了，但bitbuzz仍然不能发帖，按确认后提示“user cancelled”。

**Comment by loyloy1971** [comment]
重新登陆后可以发帖了

**Comment by AricRedemption** [comment]
> In Showmoney or Show3-v1, the balance you see might be the balance of the xpub, which includes multiple addresses. Currently, in Metalet, it shows the balance for a single address.

It's normal now, please check it. @loyloy1971
